### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by n1ckoates** [LoganDark/fabric-command-hider#2]
Is there a readily-available download for this mod, or should I build it myself? If not, consider publishing to Modrinth and/or Curseforge if it's stable enough.

**Comment by LoganDark** [comment]
https://github.com/LoganDark/fabric-command-hider/releases

**Comment by n1ckoates** [comment]
I swear I must be blind - thank you!

**Comment by LoganDark** [comment]
It's not your fault - they're marked as pre-releases so GitHub doesn't actually display them in the sidebar, only "2 tags".
